// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9sFt4ycsPnCEkJURVCpGSjyIVFVFx5to',
    appId: '1:816688949516:web:24c1a47a1ac891a3c14129',
    messagingSenderId: '816688949516',
    projectId: 'myofficehub-bb2f8',
    authDomain: 'myofficehub-bb2f8.firebaseapp.com',
    databaseURL: 'https://myofficehub-bb2f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myofficehub-bb2f8.firebasestorage.app',
    measurementId: 'G-NB0584N665',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcFHQvreKNTzSUKjh4JwlKcr0gwFSs1u4',
    appId: '1:816688949516:android:26e2d41b9e99e0d1c14129',
    messagingSenderId: '816688949516',
    projectId: 'myofficehub-bb2f8',
    databaseURL: 'https://myofficehub-bb2f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myofficehub-bb2f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI2wXRa6vuRklMMBWHSYa0upq2Vw927rU',
    appId: '1:816688949516:ios:4d5bea93e6c1ff53c14129',
    messagingSenderId: '816688949516',
    projectId: 'myofficehub-bb2f8',
    databaseURL: 'https://myofficehub-bb2f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myofficehub-bb2f8.firebasestorage.app',
    iosBundleId: 'com.myofficehub.myofficehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI2wXRa6vuRklMMBWHSYa0upq2Vw927rU',
    appId: '1:816688949516:ios:4d5bea93e6c1ff53c14129',
    messagingSenderId: '816688949516',
    projectId: 'myofficehub-bb2f8',
    databaseURL: 'https://myofficehub-bb2f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myofficehub-bb2f8.firebasestorage.app',
    iosBundleId: 'com.myofficehub.myofficehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9sFt4ycsPnCEkJURVCpGSjyIVFVFx5to',
    appId: '1:816688949516:web:5659726e138ae434c14129',
    messagingSenderId: '816688949516',
    projectId: 'myofficehub-bb2f8',
    authDomain: 'myofficehub-bb2f8.firebaseapp.com',
    databaseURL: 'https://myofficehub-bb2f8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'myofficehub-bb2f8.firebasestorage.app',
    measurementId: 'G-KZL7C3NJPL',
  );
}
